Ability to provide authentication to stratum pool
arnabk/stratum-client pull request #3
Opened 2018-08-07 12:47 UTC by KorkyMonster

Added the ability for the user to specify a worker password to authenticate. In most cases, pools will accept anything as the password and still successfully authenticate the worker, but some pools do require a password.

Also added the ability for the stratum client to detect a response from the pool and determine whether authentication succeeded or failed.

Also added a callback for Authentication Success and Authentication Fail.

2018-08-07 16:04 UTC, arnabk requested changes

2018-08-07 16:04 UTC, arnabk commented on README.md
> +If `password` if not specified, the client will attempt to authenticate with 'x', which is good enough in most cases.
@KorkyMonster I think out of all the changes, let's keep following changes

`password: "x",`

```
onAuthorizeSuccess: () => console.log('Worker authorized'),
onAuthorizeFail: () => console.log('WORKER FAILED TO AUTHORIZE OH NOOOOOO'),
```

`If password if not specified, the client will attempt to authenticate with 'x', which is good enough in most cases.`

I am bit concerned about removing `onAuthorize`. I care about those who already started using it. I want to keep it backward compatible and want to make sure that there are no major refactoring of code for those who are using it.

- We can rename onAuthorizeSuccess to onAuthorize and internally support both, but in README we document onAuthorizeSuccess so that future users do not use the old name
- We can keep onAuthorizeSuccess and onAuthorize both and point onAuthorize to onAuthorize and mark onAuthorize deprecated

2018-08-07 16:04 UTC, arnabk commented on src/processData.js
> +	}
@KorkyMonster Let's reformat it to ->

```
{
  if (result) onAuthorizeSuccess(result);
  else if (error) onAuthorizeFail(error);
}
```
I am assuming that when authentication fails, there will be error and in case of success, there will be result. You can test it out before this change. In all cases, the code could be cleaned up like above.

2018-08-07 16:04 UTC, arnabk commented on src/processData.js
> +        }
@KorkyMonster Same recommendation

```
const defaultTo = require('lodash/defaultTo');
.
.
.
if (worker) {
  client.write(authorize.replace("<worker.name>", worker).replace("<worker.pass>", defaultTo(password, 'x'));
}
.
.
```

2018-08-07 17:57 UTC, KorkyMonster commented on README.md
> +If `password` if not specified, the client will attempt to authenticate with 'x', which is good enough in most cases.
I think this is a good way to go about adding ‘onAuthorizeSuccess’ while still supporting people using ‘onAuthorize’.

I will take action on this when I get home.

2018-08-07 17:58 UTC, AnanthVivekanand commented on src/processData.js
> +        }
Will also clean up code using your recommendations!

2018-08-07 18:27 UTC, KorkyMonster commented on src/processData.js
> +	}
If the worker fails to authorize, the pool responds with `{ id: 'mining.authorize', result: false, error: null }
`.

jsonData.error will still be `null` even if authentication fails, so it cannot be used to determine whether authentication succeeded or failed. `jsonData.result` is the only indicator in the pool response that will identify whether it succeeded or failed.

I think we should use this:

```
{
  if (result) onAuthorizeSuccess(result);
  else if (!result) onAuthorizeFail(error);
}
```

2018-08-07 19:33 UTC, KorkyMonster commented
I have made the changes suggested, with the exceptions noted above in my replies to your review.

2018-08-11 01:01 UTC, arnabk approved these changes

2018-08-11 01:01 UTC, arnabk commented on src/index.js
> -        onAuthorize: null,
@KorkyMonster If `onAuthorize` is supposed to be fallback, should we not also set it to `NULL` here?

2018-08-11 01:02 UTC, merged

2018-08-11 01:11 UTC, arnabk commented
@KorkyMonster Thank you for your PR. I merged it and did some code cleanup. Pull up latest from npm and let me know if everything works for you.